src/Entity/Parts/InfoProviderReference.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts;

use App\Services\InfoProviderSystem\DTOs\SearchResultDTO;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Embeddable;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * This class represents a reference to a info provider inside a part.
 */
#[Embeddable]
class InfoProviderReference
{

    /** @var string|null The key referencing the provider used to get this part, or null if it was not provided by a data provider */
    #[Column(type: 'string', nullable: true)]
    #[Groups(['provider_reference:read'])]
    private ?string $provider_key = null;

    /** @var string|null The id of this part inside the provider system or null if the part was not provided by a data provider */
    #[Column(type: 'string', nullable: true)]
    #[Groups(['provider_reference:read'])]
    private ?string $provider_id = null;

    /**
     * @var string|null The url of this part inside the provider system or null if this info is not existing
     */
    #[Column(type: 'string', nullable: true)]
    #[Groups(['provider_reference:read'])]
    private ?string $provider_url = null;

    #[Column(type: Types::DATETIME_MUTABLE, nullable: true,  options: ['default' => null])]
    #[Groups(['provider_reference:read'])]
    private ?\DateTimeInterface $last_updated = null;

    /**
     * Constructing is forbidden from outside.
     */
    private function __construct()
    {

    }

    /**
     * Returns the key usable to identify the provider, which provided this part. Returns null, if the part was not created by a provider.
     * @return string|null
     */
    public function getProviderKey(): ?string
    {
        return $this->provider_key;
    }

    /**
     * Returns the id of this part inside the provider system or null if the part was not provided by a data provider.
     * @return string|null
     */
    public function getProviderId(): ?string
    {
        return $this->provider_id;
    }

    /**
     * Returns the url of this part inside the provider system or null if this info is not existing.
     * @return string|null
     */
    public function getProviderUrl(): ?string
    {
        return $this->provider_url;
    }

    /**
     * Gets the time, when the part was last time updated by the provider.
     * @return \DateTimeInterface|null
     */
    public function getLastUpdated(): ?\DateTimeInterface
    {
        return $this->last_updated;
    }

    /**
     * Returns true, if this part was created based on infos from a provider.
     * Or false, if this part was created by a user manually.
     * @return bool
     */
    public function isProviderCreated(): bool
    {
        return $this->provider_key !== null;
    }

    /**
     * Creates a new instance, without any provider information.
     * Use this for parts, which are created by a user manually.
     * @return InfoProviderReference
     */
    public static function noProvider(): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = null;
        $ref->provider_id = null;
        $ref->provider_url = null;
        $ref->last_updated = null;
        return $ref;
    }

    /**
     * Creates a reference to an info provider based on the given parameters.
     * @param  string  $provider_key
     * @param  string  $provider_id
     * @param  string|null  $provider_url
     * @return self
     */
    public static function providerReference(string $provider_key, string $provider_id, ?string $provider_url = null): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = $provider_key;
        $ref->provider_id = $provider_id;
        $ref->provider_url = $provider_url;
        $ref->last_updated = new \DateTimeImmutable();
        return $ref;
    }

    /**
     * Creates a reference to an info provider based on the given Part DTO
     * @param  SearchResultDTO  $dto
     * @return self
     */
    public static function fromPartDTO(SearchResultDTO $dto): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = $dto->provider_key;
        $ref->provider_id = $dto->provider_id;
        $ref->provider_url = $dto->provider_url;
        $ref->last_updated = new \DateTimeImmutable();
        return $ref;
    }
}

src/Entity/Parts/PartLot.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use App\ApiPlatform\Filter\LikeFilter;
use App\Repository\PartLotRepository;
use Doctrine\DBAL\Types\Types;
use App\Entity\Base\AbstractDBElement;
use App\Entity\Base\TimestampTrait;
use App\Entity\Contracts\NamedElementInterface;
use App\Entity\Contracts\TimeStampableInterface;
use App\Entity\UserSystem\User;
use App\Validator\Constraints\Selectable;
use App\Validator\Constraints\ValidPartLot;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * This entity describes a lot where parts can be stored.
 * It is the connection between a part and its store locations.
 *
 * @see \App\Tests\Entity\Parts\PartLotTest
 */
#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
#[ORM\Table(name: 'part_lots')]
#[ORM\Index(name: 'part_lots_idx_instock_un_expiration_id_part', columns: ['instock_unknown', 'expiration_date', 'id_part'])]
#[ORM\Index(name: 'part_lots_idx_needs_refill', columns: ['needs_refill'])]
#[ValidPartLot]
#[ApiResource(
    operations: [
        new Get(security: 'is_granted("read", object)'),
        new GetCollection(security: 'is_granted("@parts.read")'),
        new Post(securityPostDenormalize: 'is_granted("create", object)'),
        new Patch(security: 'is_granted("edit", object)'),
        new Delete(security: 'is_granted("delete", object)'),
    ],
    normalizationContext: ['groups' => ['part_lot:read', 'part_lot:read:standalone',  'api:basic:read', 'pricedetail:read'], 'openapi_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['part_lot:write', 'api:basic:write'], 'openapi_definition_name' => 'Write'],
)]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(LikeFilter::class, properties: ["description", "comment"])]
#[ApiFilter(DateFilter::class, strategy: DateFilter::EXCLUDE_NULL)]
#[ApiFilter(BooleanFilter::class, properties: ['instock_unknown', 'needs_refill'])]
#[ApiFilter(RangeFilter::class, properties: ['amount'])]
#[ApiFilter(OrderFilter::class, properties: ['description', 'comment', 'addedDate', 'lastModified'])]
class PartLot extends AbstractDBElement implements TimeStampableInterface, NamedElementInterface
{
    use TimestampTrait;

    /**
     * @var string A short description about this lot, shown in table
     */
    #[Groups(['simple', 'extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $description = '';

    /**
     * @var string a comment stored with this lot
     */
    #[Groups(['full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $comment = '';

    /**
     * @var \DateTimeInterface|null Set a time until when the lot must be used.
     *                Set to null, if the lot can be used indefinitely.
     */
    #[Groups(['extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, name: 'expiration_date', nullable: true)]
    protected ?\DateTimeInterface $expiration_date = null;

    /**
     * @var StorageLocation|null The storelocation of this lot
     */
    #[Groups(['simple', 'extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\ManyToOne(targetEntity: StorageLocation::class, fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'id_store_location')]
    #[Selectable()]
    protected ?StorageLocation $storage_location = null;

    /**
     * @var bool If this is set to true, the instock amount is marked as not known
     */
    #[Groups(['simple', 'extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $instock_unknown = false;

    /**
     * @var float The amount of parts in this lot. For integer-quantities this value is rounded to the next integer.
     */
    #[Assert\PositiveOrZero]
    #[Groups(['simple', 'extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::FLOAT)]
    protected float $amount = 0.0;

    /**
     * @var bool determines if this lot was manually marked for refilling
     */
    #[Groups(['extended', 'full', 'import', 'part_lot:read', 'part_lot:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $needs_refill = false;

    /**
     * @var Part|null The part that is stored in this lot
     */
    #[Assert\NotNull]
    #[ORM\ManyToOne(targetEntity: Part::class, inversedBy: 'partLots')]
    #[ORM\JoinColumn(name: 'id_part', nullable: false, onDelete: 'CASCADE')]
    #[Groups(['part_lot:read:standalone', 'part_lot:write'])]
    protected ?Part $part = null;

    /**
     * @var User|null The owner of this part lot
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'id_owner', onDelete: 'SET NULL')]
    #[Groups(['part_lot:read', 'part_lot:write'])]
    protected ?User $owner = null;

    public function __clone()
    {
        if ($this->id) {
            $this->addedDate = null;
        }
        parent::__clone();
    }

    /**
     * Check if the current part lot is expired.
     * This is the case, if the expiration date is greater the current date.
     *
     * @return bool|null True, if the part lot is expired. Returns null, if no expiration date was set.
     *
     * @throws Exception If an error with the DateTime occurs
     */
    public function isExpired(): ?bool
    {
        if (!$this->expiration_date instanceof \DateTimeInterface) {
            return null;
        }

        //Check if the expiration date is bigger then current time
        return $this->expiration_date < new DateTime('now');
    }

    /**
     * Gets the description of the part lot. Similar to a "name" of the part lot.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets the description of the part lot.
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Gets the comment for this part lot.
     */
    public function getComment(): string
    {
        return $this->comment;
    }

    /**
     * Sets the comment for this part lot.
     */
    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Gets the expiration date for the part lot. Returns null, if no expiration date was set.
     */
    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    /**
     * Sets the expiration date for the part lot. Set to null, if the part lot does not expire.
     *
     *
     */
    public function setExpirationDate(?\DateTimeInterface $expiration_date): self
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    /**
     * Gets the storage location, where this part lot is stored.
     *
     * @return StorageLocation|null The store location where this part is stored
     */
    public function getStorageLocation(): ?StorageLocation
    {
        return $this->storage_location;
    }

    /**
     * Sets the storage location, where this part lot is stored.
     */
    public function setStorageLocation(?StorageLocation $storage_location): self
    {
        $this->storage_location = $storage_location;

        return $this;
    }

    /**
     * Return the part that is stored in this part lot.
     */
    public function getPart(): ?Part
    {
        return $this->part;
    }

    /**
     * Sets the part that is stored in this part lot.
     */
    public function setPart(Part $part): self
    {
        $this->part = $part;

        return $this;
    }

    /**
     * Checks if the instock value in the part lot is unknown.
     */
    public function isInstockUnknown(): bool
    {
        return $this->instock_unknown;
    }

    /**
     * Set the unknown instock status of this part lot.
     */
    public function setInstockUnknown(bool $instock_unknown): self
    {
        $this->instock_unknown = $instock_unknown;

        return $this;
    }

    public function getAmount(): float
    {
        if ($this->part instanceof Part && !$this->part->useFloatAmount()) {
            return round($this->amount);
        }

        return $this->amount;
    }

    /**
     * Sets the amount of parts in the part lot.
     * If null is passed, amount will be set to unknown.
     *
     * @return $this
     */

src/Entity/Parts/PartTraits/ProjectTrait.php
<?php

declare(strict_types=1);

namespace App\Entity\Parts\PartTraits;

use App\Entity\ProjectSystem\Project;
use App\Entity\ProjectSystem\ProjectBOMEntry;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

trait ProjectTrait
{
    /**
     * @var Collection<ProjectBOMEntry> $project_bom_entries
     */
    #[ORM\OneToMany(targetEntity: ProjectBOMEntry::class, mappedBy: 'part', cascade: ['remove'], orphanRemoval: true)]
    protected Collection $project_bom_entries;

    /**
     * @var Project|null If a project is set here, then this part is special and represents the builds of a project.
     */
    #[ORM\OneToOne(targetEntity: Project::class, inversedBy: 'build_part')]
    #[ORM\JoinColumn]
    protected ?Project $built_project = null;

    /**
     *  Returns all ProjectBOMEntries that use this part.
     *
     * @phpstan-return Collection<int, ProjectBOMEntry>
     */
    public function getProjectBomEntries(): Collection
    {
        return $this->project_bom_entries;
    }

    /**
     * Checks whether this part represents the builds of a project
     * @return bool True if it represents the builds, false if not
     */
    #[Groups(['part:read'])]
    public function isProjectBuildPart(): bool
    {
        return $this->built_project !== null;
    }

    /**
     * Returns the project that this part represents the builds of, or null if it doesn't
     */
    public function getBuiltProject(): ?Project
    {
        return $this->built_project;
    }


    /**
     * Sets the project that this part represents the builds of
     * @param  Project|null  $built_project The project that this part represents the builds of, or null if it is not a build part
     */
    public function setBuiltProject(?Project $built_project): self
    {
        $this->built_project = $built_project;
        return $this;
    }


    /**
     *  Get all projects which uses this part.
     *
     * @return Project[] * all devices which uses this part as a one-dimensional array of Device objects
     *                  (empty array if there are no ones)
     *                  * the array is sorted by the devices names
     */
    public function getProjects(): array
    {
        $projects = [];

        foreach($this->project_bom_entries as $entry) {
            $projects[] = $entry->getProject();
        }

        return $projects;
    }
}

templates/parts/info/_extended_infos.html.twig
{% import "helper.twig" as helper %}

<table class="table table-striped table-hover table-sm w-100 table-responsive-sm">
    <tbody>
    <tr> {# Creation date #}
        <td>{% trans %}createdAt{% endtrans %}</td>
        <td>{{ part.addedDate | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.creating_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ creating_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# Last modified date #}
        <td>{% trans %}lastModified{% endtrans %}</td>
        <td>{{ part.lastModified | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.last_editing_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ last_editing_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# ID #}
        <td>{% trans %}id.label{% endtrans %}</td>
        <td>{{ part.iD }}</td>
    </tr>

    <tr> {# IPN #}
        <td>{% trans %}part.edit.ipn{% endtrans %}</td>
        <td>{{ part.ipn ?? 'part.ipn.not_defined'|trans }}</td>
    </tr>

    <tr> {# Favorite status #}
        <td>{% trans %}part.isFavorite{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.favorite) }}</td>
    </tr>

    <tr> {# Build status #}
        <td>{% trans %}part.is_build_part{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.projectBuildPart) }}
            {% if part.projectBuildPart %}(<a href="{{ entity_url(part.builtProject, "edit") }}">{{ part.builtProject.name }}</a>){% endif %}</td>
    </tr>

    <tr>
        <td>{% trans %}part.minOrderAmount{% endtrans %}</td>
        <td>{% if  pricedetail_helper.minOrderAmount(part) %}
                {{ pricedetail_helper.minOrderAmount(part) | format_amount(part.partUnit) }}
            {% else %}
                {% trans %}Unknown{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr>
        <td>{% trans %}part.info_provider_reference{% endtrans %}</td>
        <td>
            {% if part.providerReference.providerCreated %}
                {% if part.providerReference.providerUrl %}
                    <a href="{{ part.providerReference.providerUrl }}" rel="noopener">
                {% endif %}
                <span title="{{ part.providerReference.providerKey }}">{{ info_provider_label(part.providerReference.providerKey)|default(part.providerReference.providerKey) }}</span>: {{ part.providerReference.providerId }}
                <span> ({{ part.providerReference.lastUpdated | format_datetime() }})</span>
                {% if part.providerReference.providerUrl %}
                    </a>
                {% endif %}

                {# Show last updated date #}

            {% else %}
                {{ helper.boolean_badge(part.providerReference.providerCreated) }}
            {% endif %}

        </td>
    </tr>

    </tbody>
</table>

templates/parts/info/_history.html.twig
<div class="mt-2">
    {% if datatable is not null %}
        {% import "components/history_log_macros.html.twig" as log %}
        {{ log.element_history_component(datatable) }}
    {% endif %}
</div>

templates/parts/info/_sidebar.html.twig
{% import "helper.twig" as helper %}

{% if timeTravel is not null %}
    <b class="mb-2">{% trans with {'%timestamp%': timeTravel|format_datetime('short')} %}part.info.timetravel_hint{% endtrans %}</b>
{% endif %}

{% if part.projectBuildPart %}
    <b class="mb-2">{% trans %}part.info.projectBuildPart.hint{% endtrans %}:  <a href="{{ entity_url(part.builtProject) }}">{{ part.builtProject.name }}</a></b>
{% endif %}

<div class="mb-3">
<span class="text-muted" title="{% trans %}lastModified{% endtrans %}">
    <i class="fas fa-history fa-fw"></i>  {{ helper.entity_last_modified(part) }}
</span>
    <br>
    <span class="text-muted mt-1" title="{% trans %}createdAt{% endtrans %}">
    <i class="fas fa-calendar-plus fa-fw"></i> {{ helper.entity_created_at(part) }}
</span>
</div>

{# Part mass #}
{% if part.mass %}
    <div>
        <h6>
            <span class="badge bg-secondary" title="{% trans %}part.mass.tooltip{% endtrans %}"><i class="fas fa-weight-hanging fa-fw"></i> {{ part.mass | format_si("g") }}</span>
        </h6>
    </div>
{% endif %}

{# Needs Review tag #}
{% if part.needsReview %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-warning"><i class="fas fa-ambulance fa-fw"></i> {% trans %}part.needs_review.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{# Favorite Status tag #}
{% if part.favorite %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-success"><i class="fas fa-award fa-fw"></i> {% trans %}part.favorite.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{% if part.obsolete %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-danger"><i class="fas fa-ghost fa-fw"></i> {% trans %}part.obsolete.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{# Manufacturing status tag #}
<div class="mt-1">
    <h6>
        {{ helper.m_status_to_badge(part.manufacturingStatus) }}
    </h6>
</div>

{# Show tags #}
{% if part.tags is not empty %}
    <div class="mt-1">
        <h6 style="line-height: 1.5;">
            {{ helper.string_to_tags(part.tags) }}
        </h6>
    </div>
{% endif %}

{# Info provider badge #}
{% if part.providerReference.providerCreated %}
    <div class="mt-1">
        <h6>
            <a href="{{ part.providerReference.providerUrl ?? '#' }}" class="badge bg-info badge-info" title="{% trans %}part.info_provider_reference.badge{% endtrans %}">
                <i class="fa-solid fa-cloud"></i>
                {{ info_provider_label(part.providerReference.providerKey)|default(part.providerReference.providerKey) }}
            </a>
        </h6>
    </div>
{% endif %}

templates/parts/info/_specifications.html.twig
{# var \App\Entity\Parts\Part part #}
{% import "helper.twig" as helper %}

{% for name, parameters in part.groupedParameters %}
    {% if name is not empty %}<h5 class="mt-1">{{ name }}</h5>{% endif %}
    {{ helper.parameters_table(parameters) }}
{% endfor %}

{% if description_params is not empty %}
    <h5 class="mt-1">{% trans %}parameters.extracted_from_description{% endtrans %}</h5>
    {{ helper.parameters_table(description_params) }}
{% endif %}

{% if comment_params is not empty %}
    <h5 class="mt-1">{% trans %}parameters.auto_extracted_from_comment{% endtrans %}</h5>
    {{ helper.parameters_table(comment_params) }}
{% endif %}

templates/parts/info/_withdraw_modal.html.twig
<div class="modal fade" id="withdraw-modal" tabindex="-1" aria-labelledby="withdraw-modal-title" aria-hidden="true" {{ stimulus_controller('pages/part_withdraw_modal') }}>
    <form method="post" action="{{ path('part_add_withdraw', {"id": part.id}) }}">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="withdraw-modal-title"
                        data-withdraw="{% trans %}part.info.withdraw_modal.title.withdraw{% endtrans %}"
                        data-add="{% trans %}part.info.withdraw_modal.title.add{% endtrans %}"
                        data-move="{% trans %}part.info.withdraw_modal.title.move{% endtrans %}"
                    >Filled by JS Controller</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {# non visible form elements #}
                    <input type="hidden" name="lot_id" value="">
                    <input type="hidden" name="action" value="">
                    <input type="hidden" name="_csfr" value="{{ csrf_token('part_withraw' ~ part.iD) }}">
                    <input type="hidden" name="_redirect" value="{{ app.request.requestUri }}">

                    <div class="row mb-2">
                        <label class="col-form-label col-sm-3">
                            {% trans %}part.info.withdraw_modal.amount{% endtrans %}
                        </label>
                        <div class="col-sm-9">
                            <input type="number" required class="form-control" min="0" step="{{ (part.partUnit and not part.partUnit.integer) ? 'any' : '1' }}" name="amount" value="">
                        </div>
                    </div>

                    <div class="row mb-2 d-none" id="withdraw-modal-move-to">
                        <label class="col-form-label col-sm-3">{% trans %}part.info.withdraw_modal.move_to{% endtrans %}</label>
                        <div class="col-sm-9">
                            {% for lots in part.partLots|filter(l => l.instockUnknown == false) %}

                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="target_id" value="{{ lots.iD }}" id="modal_target_radio_{{ lots.iD }}" {% if not withdraw_add_helper.canAdd(lots) %}disabled{% endif %} required {% if loop.first %}checked{% endif %}>
                                    <label class="form-check-label" for="modal_target_radio_{{ lots.iD }}">
                                        {{ (lots.storageLocation) ? lots.storageLocation.fullPath : ("Lot " ~ loop.index) }}{% if lots.name is not empty %} ({{ lots.name }}){% endif %}: <b>{{ lots.amount | format_amount(part.partUnit) }}</b>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label class="col-form-label col-sm-3">
                            {% trans %}part.info.withdraw_modal.comment{% endtrans %}
                        </label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="comment" value="" {% if event_comment_needed('part_stock_operation') %}required{% endif %}>
                            <div id="emailHelp" class="form-text">{% trans %}part.info.withdraw_modal.comment.hint{% endtrans %}</div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans %}modal.close{% endtrans %}</button>
                    <button type="submit" class="btn btn-primary">{% trans %}modal.submit{% endtrans %}</button>
                </div>
            </div>
        </div>
    </form>
</div>